name: Validation
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version-file: .node-version, cache: yarn }
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn format:check
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
      - run: yarn build
      - run: yarn test:e2e
